local AudioFileNames: { [string]: string } = {
	["Clickv4"] 			= "Clickv4",
	["popv2"] 				= "popv2",
	["CountDownGo"] 		= "CountDownGo",
	["CountDown321"] 		= "CountDown321",
	["NegativeClick"] 		= "NegativeClick",
	["Clickv2"] 			= "Clickv2",
	["Clickv3"] 			= "Clickv3",
	["submitv4"] 			= "submitv4",
	["submitv3"] 			= "submitv3",
	["submit"] 				= "submit",
	["RoundLast5Sec"] 		= "RoundLast5Sec",
	["Reset"] 				= "Reset",
	["RemoveClothes"] 		= "RemoveClothes",
	["PositiveClick"] 		= "PositiveClick",
	["ClickFx0201CombNEG"] 	= "ClickFx0201CombNEG",
	["ClickFx0201Comb"] 	= "ClickFx0201Comb",
	["Atmosphere002"] 		= "Atmosphere002",
	["RoundChange"]			= "RoundChange"
}

return AudioFileNames